python train_continual.py --dim-proto 16 \
--dim-cls 16 \
--batch-size 100 \
--test-batch-size 4000 \
--devices 0 \
--num-epochs 90 \
--proto_est_epo 35 \
--proto_cls_epo 50 \
--data_name citeseer \
--lr-decay 35 35 \
--n_nbs_per_hop 5 7 \
--n_AFE_a_select 1 \
--n_AFE_r_select 2 \
--atom_t 0.2